image: "ruby:2.5"

services:
  - mdillon/postgis:10-alpine

variables:
  RAILS_ENV: test
  POSTGRES_DB: shamap_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""
  BUNDLE_PATH: vendor/bundle

before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc)
  - bundle exec rake db:create db:schema:load

cache:
  key: #{CI_COMMIT_REF_SLUG}
  paths:
    - vendor/bundle

rspec:
  stage: test
  script:
    - bundle exec rspec
  artifacts:
    paths:
      - coverage/

pages:
  stage: deploy
  dependencies:
    - rspec
  script:
    - mv coverage/ public/
  artifacts:
    paths:
      - public
    expire_in: 30 days
  only:
    - master

rubocop:
  stage: test
  script:
    - bundle exec rubocop
