image: "ruby:2.5"

services:
  - postgres:latest

variables:
  RAILS_ENV: test
  POSTGRES_DB: shamap_test
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: ""

before_script:
  - apt-get update -qq && apt-get install -y -qq postgresql postgresql-contrib libpq-dev cmake nodejs
  - ruby -v
  - which ruby
  - gem install bundler --no-ri --no-rdoc
  - bundle install --jobs $(nproc) --path vendor
  - bundle exec rake db:create db:schema:load

cache:
  key: #{CI_COMMIT_REF_SLUG}
  paths:
    - vendor/ruby

rspec:
  script:
    - bundle exec rspec

rubocop:
  script:
    - bundle exec rubocop
