version: '3'
services:
  db:
    image: postgres:10.4-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    env_file: .env
    command: bundle exec rails s -p ${PORT:-3000} -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - ${PORT:-3000}:${PORT:-3000}
    depends_on:
      - db
