version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    env_file: .env
    command: rails s -p ${WEB_PORT:-3000} -b '0.0.0.0'
    volumes:
      - .:/myapp
      - gems:/usr/local/bundle
    ports:
      - ${WEB_PORT:-3000}:${WEB_PORT:-3000}
    links:
      - db

volumes:
  gems:
    driver: local
