version: '3'
services:
  db:
    image: mdillon/postgis:10-alpine
    volumes:
      - ./tmp/db:/var/lib/postgresql/data

  web:
    build:
      context: .
      dockerfile: web.Dockerfile
    env_file: .env
    environment:
      - BUNDLE_PATH=vendor/bundle
    command: bundle exec rails s -p ${WEB_PORT:-3000} -b '0.0.0.0'
    volumes:
      - .:/myapp
    ports:
      - ${WEB_PORT:-3000}:${WEB_PORT:-3000}
    links:
      - db
